language: d

d:
  - dmd-2.070.0
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - ldc-0.16.1
  - ldc-0.15.1
  - gdc-5.2.0
  - gdc-4.9.2

addons:
  apt:
    packages:
    - libev-dev

env:
  - VIBED_DRIVER=libevent BUILD_EXAMPLE=1 RUN_TEST=1
  - VIBED_DRIVER=libev BUILD_EXAMPLE=0 RUN_TEST=0
  - VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0

matrix:
  exclude:
    - d: ldc-0.16.1
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: ldc-0.15.1
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: gdc-5.2.0
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: gdc-4.9.2
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0

script: ./travis-ci.sh

services:
  - mongodb
  - redis-server

sudo: false
