language: d

d:
  - dmd-2.067.1

before_install:
  - wget http://dist.schmorp.de/libev/Attic/libev-4.19.tar.gz
  - tar -xf libev-4.19.tar.gz
  - (cd libev-4.19 && ./configure && make)

env:
  - VIBED_DRIVER=libevent
  - VIBED_DRIVER=libev-travis
  - VIBED_DRIVER=libasync_botan

script:
  - dub test --compiler=$DC --config=${VIBED_DRIVER} || exit 1
  - if [ ${VIBED_DRIVER} == "libasync_botan" ]; then
      for ex in `\ls -1 examples/`; do (echo "[INFO] Building example $ex"; cd examples/$ex && dub build --compiler=$DC) || exit 1; done
    fi
  - if [ ${VIBED_DRIVER} == "libasync_botan" ]; then
      for ex in `\ls -1 tests/`; do (echo "[INFO] Running test $ex"; cd tests/$ex && dub --compiler=$DC) || exit 1; done
    fi


services:
  - mongodb
  - redis-server

sudo: false
