language: d

d:
  - dmd-2.068.0-b1
  - dmd-2.067.1
  - dmd-2.066.1
  - dmd-2.065.0
  - ldc-0.14.0
  - ldc-0.15.1
  - gdc-4.9.0
  - gdc-4.9.2

addons:
  apt:
    packages:
    - libev-dev

env:
  - VIBED_DRIVER=libevent BUILD_EXAMPLE=1 RUN_TEST=1
  - VIBED_DRIVER=libev
  - VIBED_DRIVER=libasync

matrix:
  exclude:
    - d: dmd-2.065.0
      env: VIBED_DRIVER=libasync
    - d: ldc-0.14.0
      env: VIBED_DRIVER=libasync
    - d: ldc-0.15.1
      env: VIBED_DRIVER=libasync
    - d: gdc-4.9.0
      env: VIBED_DRIVER=libasync
    - d: gdc-4.9.2
      env: VIBED_DRIVER=libasync

script:
  - dub test --compiler=$DC --config=${VIBED_DRIVER} || exit 1
  - if [ ! -z ${BUILD_EXAMPLE+x} ]; then
      for ex in `\ls -1 examples/`; do (echo "[INFO] Building example $ex"; cd examples/$ex && dub build --compiler=$DC) || exit 1; done
    fi
  - if [ ! -z ${RUN_TEST+x} ]; then
      for ex in `\ls -1 tests/`; do (echo "[INFO] Running test $ex"; cd tests/$ex && dub --compiler=$DC) || exit 1; done
    fi


services:
  - mongodb
  - redis-server

sudo: false
