language: d
dist: xenial

services:
  - mongodb
  - redis-server

addons:
  apt:
    packages:
      - gdb
      - pkg-config
      - zlib1g-dev
      - libevent-dev
      - libssl-dev

branches:
  only:
  - master
  - 0.7.x

# Enable core dumps
before_script:
  - ulimit -c unlimited -S
  - sudo mkdir /cores/ && sudo chmod 777 /cores/
  - echo "/cores/%E.%p" | sudo tee /proc/sys/kernel/core_pattern

after_failure:
  - ./scripts/core-dump.sh

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  # only the latest 4 and the oldest supported versions of each compiler
  # are present to reduce the overall CI time
  - dmd-2.089.0,dub
  - dmd-2.088.1,dub
  - dmd-2.077.1,dub
  - ldc-1.18.0,dub
  - ldc-1.17.0,dub
  - ldc-1.7.0,dub
  - dmd-2.085.0,dub # 2.085.1 has a regression
  - dmd-2.084.1,dub
  - dmd-2.078.3,dub
  - dmd-beta,dub

env:
  - VIBED_DRIVER=vibe-core PARTS=builds,unittests,examples,tests,mongo

matrix:
  include:
    - d: dmd
      env: DFLAGS="-cov -version=VibedSetCoverageMerge" PARTS=unittests,tests

#before_install:
#  - pyenv global system 3.6
#  - pip3 install 'meson==0.47.2' # pinned until the meson#4248 fix is released

#install:
#  - mkdir .ntmp
#  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
#  - unzip .ntmp/ninja-linux.zip -d .ntmp
#
#before_script:
#  - export PATH=$PATH:$PWD/.ntmp

script: ./travis-ci.sh
after_success:
 - bash <(curl -s https://codecov.io/bash)
